@startuml

[*] --> STARTED : start by request

STARTED --> CATEGORY_PROCESSING : request all categories

CATEGORY_PROCESSING --> MAKING_CSV_FILES : request products of current category

MAKING_CSV_FILES --> CATEGORY_PROCESSING : categories are not over

MAKING_CSV_FILES --> MAKING_ZIP_ARCHIVES : categories are over

MAKING_ZIP_ARCHIVES --> IDLE : finish making archives

IDLE --> IDLE : send email

IDLE --> [*]

CATEGORY_PROCESSING : queue of categories sorted in alphabetical order
MAKING_CSV_FILES : make csv files up to brand and category
MAKING_ZIP_ARCHIVES : make zip for each brand

@enduml